'use client';

import { useEffect, useState } from 'react';

type Tab = 'source' | 'bill' | 'heal';
const tabs = [
  { id: 'source' as Tab, label: 'SOURCE', kicker: 'Detect', text: 'Turn a plume into a named source.' },
  { id: 'bill' as Tab, label: 'BILL', kicker: 'Account', text: 'Make the cost of inaction visible.' },
  { id: 'heal' as Tab, label: 'HEAL', kicker: 'Resolve', text: 'Keep watching until the fix is verified.' },
];
const timeline = [
  ['detected', 'Detected', 'Plume threshold crossed', '09 Sep 2026 · 08:12 UTC'],
  ['source_named', 'Source named', 'North separator · flange F-14', '09 Sep 2026 · 11:36 UTC'],
  ['billed', 'Billed', '12.4 t CH₄ loss booked', '10 Sep 2026 · 09:05 UTC'],
  ['repair_scheduled', 'Repair scheduled', 'Field crew · work order WO-284', '11 Sep 2026 · 14:20 UTC'],
  ['resolved', 'Resolved', 'Post-repair scan below threshold', '14 Sep 2026 · 16:42 UTC'],
] as const;
const money = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(n);

function Mark() { return <span className="mark" aria-hidden="true"><i /><i /><i /></span>; }
function Count({ value, decimals = 0, prefix = '', suffix = '' }: { value: number; decimals?: number; prefix?: string; suffix?: string }) {
  const [n, setN] = useState(0);
  useEffect(() => {
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) { setN(value); return; }
    let start = 0; let frame = 0;
    const run = (time: number) => { if (!start) start = time; const p = Math.min((time - start) / 900, 1); setN(value * (1 - Math.pow(1 - p, 3))); if (p < 1) frame = requestAnimationFrame(run); };
    frame = requestAnimationFrame(run); return () => cancelAnimationFrame(frame);
  }, [value]);
  return <>{prefix}{n.toLocaleString('en-US', { minimumFractionDigits: decimals, maximumFractionDigits: decimals })}{suffix}</>;
}
function Icon({ kind }: { kind: Tab }) { return <svg viewBox="0 0 24 24" aria-hidden="true">{kind === 'source' ? <><circle cx="12" cy="12" r="8" /><path d="M12 12 18 6M5 7a10 10 0 0 0 0 10M19 7a10 10 0 0 1 0 10" /></> : kind === 'bill' ? <><path d="M6 3.5h12v17l-3-1.8-3 1.8-3-1.8-3 1.8z" /><path d="M9 8h6M9 12h6M9 16h3" /></> : <><path d="m3.8 20.2 2.7-.7 10.9-10.9-4-4L2.5 15.5l-.7 2.7 2 2Z" /><path d="m13.1 6.9 4 4M16.5 3.5l4 4" /></>}</svg>; }

function SourceMap() { return <div className="map-wrap"><div className="map-top"><span><i className="live-dot" /> S2L SCAN · TILE 09.14.26</span><span>N ↑ · LOCAL GEOMETRY</span></div><svg className="map" viewBox="0 0 860 440" role="img" aria-labelledby="map-title map-desc"><title id="map-title">Methane plume source attribution</title><desc id="map-desc">An animated teal plume trails downwind from a candidate flange source with a back-traced line and wind arrow.</desc><defs><linearGradient id="pg" x1="0" x2="1"><stop stopColor="#55e0c2" stopOpacity=".9" /><stop offset="1" stopColor="#1d6c71" stopOpacity=".04" /></linearGradient><radialGradient id="hot"><stop stopColor="#ffd078" /><stop offset="1" stopColor="#ed9065" stopOpacity="0" /></radialGradient><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 10 5 0 10Z" fill="#88f5d7" /></marker></defs><rect width="860" height="440" rx="18" fill="#0b1a1c" /><g className="grid"><path d="M40 80h780M40 160h780M40 240h780M40 320h780M140 32v376M280 32v376M420 32v376M560 32v376M700 32v376" /></g><path className="contour" d="M52 110c104-42 166 28 271-4s174-9 262 22 167-28 245-4M55 342c108-48 202 22 292-17s154-28 238 8 159 5 220-14" /><path className="road" d="M70 380c135-39 188-99 279-92s157 63 243 40 131-76 225-91M92 70c85 42 116 109 204 129s142-1 207 45 124 75 248 65" /><path className="plume" d="M184 282c70-44 102-102 182-127 77-24 131-4 208-31 87-30 153-65 242-65-50 41-98 86-153 116-71 39-125 28-205 60-82 33-153 99-274 122Z" fill="url(#pg)" /><path className="edge" d="M204 275c70-37 109-89 174-111 82-28 130-3 208-29 65-22 132-57 202-65" /><path className="candidate" d="M184 291c79-43 119-77 191-104 84-31 131-26 213-52" markerEnd="url(#arrow)" /><circle className="hotspot" cx="184" cy="291" r="44" fill="url(#hot)" /><g className="marker"><circle className="pulse" cx="184" cy="291" r="24" /><circle cx="184" cy="291" r="9" /><path d="M184 301v20" /></g><g className="sensors"><circle cx="306" cy="202" r="6" /><circle cx="420" cy="164" r="6" /><circle cx="548" cy="132" r="6" /><circle cx="680" cy="88" r="6" /></g><line className="wind" x1="685" y1="350" x2="760" y2="350" markerEnd="url(#arrow)" /><text className="svg-label bright" x="687" y="329">WIND 3.8 m/s</text><text className="svg-label" x="687" y="373">NW · 312°</text><text className="svg-label bright" x="93" y="350">CANDIDATE SOURCE</text><text className="svg-label" x="93" y="371">NORTH SEPARATOR / FLANGE F-14</text><text className="svg-label" x="51" y="55">SAMPLE TILE · 28.08830° N / 9.78350° E</text><text className="svg-label" x="714" y="405">200 m</text><path className="scale" d="M714 388h96M714 388v8M810 388v8" /></svg><div className="legend"><span><i className="lp" /> methane concentration</span><span><i className="ls" /> back-traced source</span><span><i className="ln" /> sensor track</span></div></div>; }
function Source() { return <section className="module" aria-labelledby="source-title"><div className="section-head"><div><p className="eyebrow">Sample observation · 14 Sep 2026</p><h2 id="source-title">Back-trace the plume.</h2><p className="lede">A detection becomes useful when its signal resolves to an accountable piece of equipment.</p></div><span className="status"><i className="live-dot" /> SAMPLE LIVE</span></div><div className="source-grid"><div className="panel map-panel"><SourceMap /></div><aside className="source-aside"><div className="panel confidence"><div className="label-row"><span>Attribution result</span><b>HIGH</b></div><strong>87<small>%</small></strong><p>Heuristic confidence from plume shape, wind alignment, and facility geometry.</p><div className="confidence-bar"><i /></div><div className="split"><span><b>3.8 m/s</b> wind</span><span><b>NW ↗</b> direction</span></div></div><div className="panel coords"><p className="eyebrow">Back-traced candidate</p><h3>North separator <span>↗</span> flange F-14</h3><dl><div><dt>Latitude</dt><dd>28.08830° N</dd></div><div><dt>Longitude</dt><dd>9.78350° E</dd></div><div><dt>Estimated flux</dt><dd>9,640 kg CH₄/h</dd></div></dl><p className="note">Candidate point is back-traced upwind from the brightest plume pixels. Sample attribution, not a live alert.</p></div></aside></div></section>; }

function Bill() { return <section className="module" aria-labelledby="bill-title"><div className="section-head"><div><p className="eyebrow">Sample case · financial lens</p><h2 id="bill-title">Put a price on waiting.</h2><p className="lede">The same 12.4-ton sample loss reads differently to an operator, a regulator, and a climate ledger. Keep every convention visible.</p></div><div className="total"><span>FINANCIAL EXPOSURE</span><b><Count value={21774.4} prefix="$" /></b><small>commodity + EPA climate damage</small></div></div><div className="bill-grid"><div className="panel ledger"><div className="label-row"><span>Impact ledger</span><em>SAMPLE DATA</em></div><div className="impact-group"><div className="group-label"><span>Financial loss · USD</span><span>$21,774.40 total</span></div><div className="impact"><div><span>Lost-gas commodity</span><b><Count value={1934.4} prefix="$" /></b></div><i className="commodity" /><small>at $3 / MMBtu</small></div><div className="impact"><div><span>EPA climate damage</span><b><Count value={19840} prefix="$" /></b></div><i className="damage" /><small>2020 USD screening value</small></div></div><div className="impact-group footprint"><div className="group-label"><span>Physical footprint · tCO₂e</span><span>separate unit</span></div><div className="impact"><div><span>Climate footprint</span><b><Count value={347.2} decimals={1} suffix=" t" /></b></div><i /><small>GWP100 = 28 methane conversion</small></div><div className="demo-value"><span>Demo price equivalent</span><b><Count value={26040} prefix="$" /></b><small>at clearly stated $75 / tCO₂e · not added to USD loss bars</small></div></div></div><div className="bill-side"><div className="panel detected"><span>Detected methane</span><b><Count value={12.4} decimals={1} /></b><small>metric tons CH₄</small><div className="spark"><i /><i /><i /><i /><i /><i /><i /></div></div><div className="panel formula"><div className="label-row"><span>Transparent math</span><b>∑</b></div><h3>One sample, four views.</h3><div className="formula-list"><div><span>Lost gas</span><code>12.4 t × 52 MMBtu/t × $3</code><b>$1,934.40</b></div><div><span>EPA climate damage</span><code>12.4 t × $1,600 / t CH₄</code><b>$19,840</b></div><div><span>CO₂e</span><code>12.4 t × GWP 28</code><b>347.2 t</b></div><div><span>Carbon-price value</span><code>347.2 t × $75 / tCO₂e</code><b>$26,040</b></div></div></div></div></div><div className="conventions"><b className="eyebrow">Source conventions</b><span><b>52 MMBtu / metric ton CH₄</b> · conversion</span><span><b>$3 / MMBtu</b> · Henry Hub</span><span><b>$1,600 / metric ton CH₄</b> · EPA 2023</span><span><b>$75 / tCO₂e</b> · demo price</span></div></section>; }

function Heal() { return <section className="module" aria-labelledby="heal-title"><div className="section-head"><div><p className="eyebrow">Sample case · operations loop</p><h2 id="heal-title">Close the loop, not just the ticket.</h2><p className="lede">A source only becomes resolved when the repair is scheduled, completed, and checked by another observation.</p></div><div className="resolved"><b>✓</b><span>RESOLVED<small>verified 14 Sep 2026</small></span></div></div><div className="heal-grid"><div className="panel timeline-panel"><div className="label-row"><div><p className="eyebrow">Case MTH-0247</p><h3>North separator <span>↗</span> flange F-14</h3></div><em>SAMPLE TIMELINE</em></div><div className="timeline">{timeline.map(([stage, label, detail, time]) => <div className={`event ${stage}`} key={stage}><i>{stage === 'resolved' ? '✓' : ''}</i><div><div><b>{label}</b><time>{time}</time></div><p>{detail}</p></div></div>)}</div></div><div className="heal-side"><div className="panel playbook"><div className="label-row"><div><p className="eyebrow">Repair playbook</p><h3>Make field action obvious.</h3></div><b className="play-icon">↗</b></div><div className="repair"><div><span>F-14</span><section><p className="eyebrow">Observed pattern</p><h4>Flange leak</h4><p>Likely gasket compression loss at the north separator outlet.</p></section></div><b>↓</b><div className="fix"><span>FIX</span><section><p className="eyebrow">Recommended action</p><h4>Torque and reseal</h4><p>Isolate line, torque fasteners, replace gasket, then rescan.</p></section></div></div></div><div className="panel economics"><p className="eyebrow">Repair economics</p><h3>Fix it before the next shift.</h3><div className="econ-row"><span>Estimated fix cost</span><b>{money(2400)}</b></div><div className="econ-row"><span>Current daily burn</span><b>{money(161.2)} <small>/ day</small></b></div><div className="cost-bars"><div><span>REPAIR</span><i style={{ width: '18%' }} /></div><div><span>BURN · 12 DAYS</span><i /></div></div><div className="payback"><span>Payback on repair</span><b>14.9 days</b><small>Sample assumption: $1,934.40 commodity loss spread across a 12-day observation window.</small></div></div></div></div></section>; }

export default function Home() { const [active, setActive] = useState<Tab>('source'); const current = tabs.find((x) => x.id === active) ?? tabs[0]; return <main className="shell"><header className="topbar"><a className="brand" href="#top"><Mark /> <span>METHANE <b>COPILOT</b></span></a><div className="top-right"><span className="system"><i className="live-dot" /> MARS-S2L v1 · live scan</span><span>LOCAL DEMO <em /> NO API KEYS</span></div></header><section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">Operational methane intelligence</p><h1>We don&apos;t just find methane leaks. <em>We watch until they&apos;re fixed.</em></h1><p className="hero-lede">A field-ready operating story for turning an invisible loss into a named source, a defensible bill, and a verified repair.</p><div className="loop"><b>DETECT</b><i>↗</i><span>BILL</span><i>↗</i><span>HEAL</span><i>↗</i></div></div><div className="orbit" aria-hidden="true"><div /><div /><strong><Mark /> CH₄</strong><small>signal</small><small>action</small><small>proof</small></div></section><nav className="tabs" aria-label="Demo pillars" role="tablist">{tabs.map((tab, i) => <button key={tab.id} role="tab" aria-selected={active === tab.id} aria-controls={`${tab.id}-panel`} className={active === tab.id ? 'selected' : ''} onClick={() => setActive(tab.id)}><small>0{i + 1}</small><span className="tab-icon"><Icon kind={tab.id} /></span><span><b>{tab.label}</b><em>{tab.text}</em></span><i>↗</i></button>)}</nav><div className="content-heading"><div><p className="eyebrow">{current.kicker} / 0{tabs.findIndex((x) => x.id === active) + 1}</p><h2>{current.text}</h2></div><p>All visuals are local geometry<br />and baked-in sample data.</p></div><div id="source-panel" role="tabpanel" hidden={active !== 'source'}>{active === 'source' && <Source />}</div><div id="bill-panel" role="tabpanel" hidden={active !== 'bill'}>{active === 'bill' && <Bill />}</div><div id="heal-panel" role="tabpanel" hidden={active !== 'heal'}>{active === 'heal' && <Heal />}</div><footer><span><Mark /> Methane Copilot</span><span>DETECT ↗ BILL ↗ HEAL</span><span>Local demo · v1.0</span></footer></main>; }
